version: "3.0.1"

services:

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: order-postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - order-net

  redis:
    image: redis:latest
    container_name: order-redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - order-net

networks:
  order-net:
    driver: bridge
